//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



[Serializable()]
public class Role
{
    
    public int Id;
    
    public string Name;
    
    public SpiritualRootEnum Spiritual;
    
    public SidelineEnum Sideline;
}

[Serializable()]
public enum SidelineEnum
{
    
    Pharm,
    
    Smith,
    
    Farmer,
    
    Chef,
    
    Null,
}

[Serializable()]
public enum SpiritualRootEnum
{
    
    Gold,
    
    Wood,
    
    Water,
    
    Fire,
    
    Earth,
}
